### PR TITLE
Make all shell scripts executable

### PR DESCRIPTION
**Pull request by jameswilson**
First, Thanks @greg0ire! This is a really cool project! I love it!

On a clean clone on MacOS Sierra,  various shell files are created without the executable bit.

```
$ find . -name "*.sh" -exec ls -al {} \;
-rwxr-xr-x  1 jameswilson  staff  551 Mar  1 09:06 ./configure.sh
-rwxr-xr-x  1 jameswilson  staff  1148 Mar  1 09:06 ./hooks/change_detector.sh
-rw-r--r--  1 jameswilson  staff  1266 Mar  1 09:06 ./hooks/git_config_wrapper.sh
-rw-r--r--  1 jameswilson  staff  707 Mar  1 09:06 ./hooks/hook_switcher.sh
-rw-r--r--  1 jameswilson  staff  671 Mar  1 09:06 ./hooks/php/composer/react.sh
-rwxr-xr-x  1 jameswilson  staff  414 Mar  1 09:06 ./hooks/php/ctags/configure.sh
-rwxr-xr-x  1 jameswilson  staff  198 Mar  1 09:06 ./hooks/php/sismo/configure.sh
-rwxr-xr-x  1 jameswilson  staff  89 Mar  1 09:06 ./hooks/syntaxchecker/php.sh
-rw-r--r--  1 jameswilson  staff  94 Mar  1 09:06 ./hooks/syntaxchecker/xlf.sh
```

This commit is the result of the following command:
```
find . -name "*.sh" -exec chmod +x {} \;
```

which fixed 4 files above:

```
$ find . -name "*.sh" -exec ls -al {} \;
-rwxr-xr-x  1 jameswilson  staff  551 Mar  1 09:06 ./configure.sh
-rwxr-xr-x  1 jameswilson  staff  1148 Mar  1 09:06 ./hooks/change_detector.sh
-rwxr-xr-x  1 jameswilson  staff  1266 Mar  1 09:06 ./hooks/git_config_wrapper.sh
-rwxr-xr-x  1 jameswilson  staff  707 Mar  1 09:06 ./hooks/hook_switcher.sh
-rwxr-xr-x  1 jameswilson  staff  671 Mar  1 09:06 ./hooks/php/composer/react.sh
-rwxr-xr-x  1 jameswilson  staff  414 Mar  1 09:06 ./hooks/php/ctags/configure.sh
-rwxr-xr-x  1 jameswilson  staff  198 Mar  1 09:06 ./hooks/php/sismo/configure.sh
-rwxr-xr-x  1 jameswilson  staff  89 Mar  1 09:06 ./hooks/syntaxchecker/php.sh
-rwxr-xr-x  1 jameswilson  staff  94 Mar  1 09:06 ./hooks/syntaxchecker/xlf.sh
```

I've also manually reviewed all of the other `pre-` and `post-`  files, and all of them do have the executable bit set correctly.

Finally, a separate issue, I've tried running `tests/all.sh`  per your contribution guidelines, but it seems that it doesn't work correctly on my environment. I believe the issues I'm seeing are unrelated to this change.

### CODE REVIEW

**Comment by greg0ire** [comment]
> First, Thanks @greg0ire! This is a really cool project! I love it!

Glad you like it :)

Regarding your issue, that's a bit strange, I don't think any of these files are supposed to be executed directly, they are just sourced with `.` Maybe `.` is not the way to go, and there is another way that also works on MacOS? Can you try `source change_detector.sh`, see if MacOS complains about it not being executable, as it probably already does when you use `.` ?

**Comment by jameswilson** [comment]
Oh, hmm.... interesting.   So, I just tested using `source` on a random script.sh file that did not have executable bit set, and got no problem.   So possibly there is no problem here after all.  I just found it weird that *some* shell scripts were executable while others were not, in the same directory. If this is in fact by design, maybe some other construct that makes it clearer that *some* of the sh files are not intended to be executed manually, would be helpful.

**Comment by greg0ire** [comment]
[As you can see](https://github.com/greg0ire/git_template/blob/master/template/hooks/change_detector.sh), the scripts do not do anything, they define functions that can then be used in other scripts.

> If this is in fact by design, maybe some other construct that makes it clearer that some of the sh files are not intended to be executed manually, would be helpful.

Good idea, not sure what would be a good marker for that though.

> If the intention here is to just leave as is (works as designed), I'd recommend at least double check to confirm that any scripts that were not intended to be executed but just sourced have the executable bit removed -- you'd have a better idea than me of which ones they might be.

The only script that shouldn't have the flag is… `change_detector.sh`. Do you want to contribute that change?

**Comment by greg0ire** [comment]
ping @jameswilson

**Comment by jameswilson** [comment]
Got distracted on other things.  Once I was able to pick this up again, I ran into more mac compatibility issues with your scripts, there are a number of gnu command line options for various scripts that are not BSD compatible. (Totally unrelated to this issue, but wanted to just let you know)  I’m going to work on those issues when I get a chance.  I had to put this on pause to get some other work done, but want to come back to revisit.  

Would you be amenable to accepting Mac//BSD Compatibility pull requests?

**Comment by greg0ire** [comment]
> Would you be amenable to accepting Mac//BSD Compatibility pull requests?

Yes, completely!

**Comment by greg0ire** [comment]
Monthly ping @jameswilson

**Comment by greg0ire** [comment]
@jameswilson please respond

**Comment by alanpoulain** [comment]
@greg0ire I'm on Linux and I had to make `hook_switcher.sh` executable for `configure.sh` to work.
Else I have the error:
```

**Pull request closed without merging**
