### PR TITLE
Update react.sh

### PR DESCRIPTION
**Pull request by Torgan**
Remove dev option 

It has been deprecated

### CODE REVIEW

**Comment by greg0ire** [comment]
Good catch! Could you please change the commit message to 

```
Remove dev option 

It has been deprecated
```

?

**Comment by Torgan** [comment]
Here we go :)

**Comment by greg0ire** [comment]
Not what I meant, but nevermind, I fixed it for you. Thanks a lot!

**Comment by greg0ire** [comment]
Here is a good article about commit messages, if you are interested : http://rakeroutes.com/blog/deliberate-git/

**Pull request closed without merging**
